module.exports = {
  rules: {
    'color-no-invalid-hex': true,
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'named-grid-areas-no-invalid': true,
    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'string-no-newline': true,
    'property-no-unknown': true,
    'keyframe-declaration-no-important': true,
    'declaration-block-no-duplicate-custom-properties': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'block-no-empty': true,
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'media-feature-name-no-unknown': true,
    'at-rule-no-unknown': true,
    'comment-no-empty': true,
    'no-descending-specificity': true,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-source': true,
    'no-invalid-double-slash-comments': true,
    'no-invalid-position-at-import-rule': true,
    'alpha-value-notation': 'number',
    'hue-degree-notation': 'angle',
    'color-function-notation': 'modern',
    'length-zero-no-unit': true,
    'selector-pseudo-element-colon-notation': 'double',
    'font-weight-notation': 'numeric',
    'number-max-precision': 4,
    'shorthand-property-no-redundant-values': true,
    'declaration-block-single-line-max-declarations': 1,
    'no-unknown-animations': true,
    'color-hex-length': 'short',
    'font-family-name-quotes': 'always-unless-keyword',
    'function-name-case': 'lower',
    'function-url-quotes': 'always',
    'value-keyword-case': 'lower',
    'selector-attribute-quotes': 'always',
    'selector-type-case': 'lower',
    'rule-empty-line-before': ['always', { except: ['after-single-line-comment', 'first-nested'] }],
    'at-rule-empty-line-before': [
      'always',
      { except: ['blockless-after-same-name-blockless', 'blockless-after-blockless', 'first-nested'] },
    ],
    'comment-whitespace-inside': 'always',
    'no-irregular-whitespace': true,
  },
}
